# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deployment

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/libs
        
  send-jar:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Send jar to remote server
        uses: appleboy/scp-action@master
        with:
          host: 144.24.77.45
          username: ubuntu
          source: "devblog-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntn"
          key: ${{ secrets.PRIVATE_KEY }}
#         shell: bash
#         run: scp ~/devblog/build/libs/devblog-0.0.1-SNAPSHOT.jar opc@144.24.77.45:/home/opc

#         run: | 
#           scp ~/devblog/build/libs/devblog-0.0.1-SNAPSHOT.jar opc@144.24.77.45:/home/opc
#       - name: Send jar to remote server
      
